---
language: node_js
node_js:
  - "10"

dist: xenial

addons:
  chrome: stable
  firefox: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

env:
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-3.0
  - EMBER_TRY_SCENARIO=ember-lts-3.4
  - EMBER_TRY_SCENARIO=ember-lts-3.8
  - EMBER_TRY_SCENARIO=ember-lts-3.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-default

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
